// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInfo.proto

package com.data;

public final class UserInfo {
  private UserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface uInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 uid = 1;
    /**
     * <code>required int32 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int32 uid = 1;</code>
     */
    int getUid();

    // required string un = 2;
    /**
     * <code>required string un = 2;</code>
     */
    boolean hasUn();
    /**
     * <code>required string un = 2;</code>
     */
    java.lang.String getUn();
    /**
     * <code>required string un = 2;</code>
     */
    com.google.protobuf.ByteString
        getUnBytes();

    // required string pass = 3;
    /**
     * <code>required string pass = 3;</code>
     */
    boolean hasPass();
    /**
     * <code>required string pass = 3;</code>
     */
    java.lang.String getPass();
    /**
     * <code>required string pass = 3;</code>
     */
    com.google.protobuf.ByteString
        getPassBytes();

    // required string nn = 4;
    /**
     * <code>required string nn = 4;</code>
     */
    boolean hasNn();
    /**
     * <code>required string nn = 4;</code>
     */
    java.lang.String getNn();
    /**
     * <code>required string nn = 4;</code>
     */
    com.google.protobuf.ByteString
        getNnBytes();

    // required int32 sex = 5;
    /**
     * <code>required int32 sex = 5;</code>
     */
    boolean hasSex();
    /**
     * <code>required int32 sex = 5;</code>
     */
    int getSex();

    // required int32 ico = 6;
    /**
     * <code>required int32 ico = 6;</code>
     */
    boolean hasIco();
    /**
     * <code>required int32 ico = 6;</code>
     */
    int getIco();
  }
  /**
   * Protobuf type {@code com.data.uInfo}
   */
  public static final class uInfo extends
      com.google.protobuf.GeneratedMessage
      implements uInfoOrBuilder {
    // Use uInfo.newBuilder() to construct.
    private uInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private uInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final uInfo defaultInstance;
    public static uInfo getDefaultInstance() {
      return defaultInstance;
    }

    public uInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private uInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              un_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              pass_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              nn_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sex_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ico_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.data.UserInfo.internal_static_com_data_uInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.data.UserInfo.internal_static_com_data_uInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.data.UserInfo.uInfo.class, com.data.UserInfo.uInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<uInfo> PARSER =
        new com.google.protobuf.AbstractParser<uInfo>() {
      public uInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new uInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<uInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>required int32 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    // required string un = 2;
    public static final int UN_FIELD_NUMBER = 2;
    private java.lang.Object un_;
    /**
     * <code>required string un = 2;</code>
     */
    public boolean hasUn() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string un = 2;</code>
     */
    public java.lang.String getUn() {
      java.lang.Object ref = un_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          un_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string un = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUnBytes() {
      java.lang.Object ref = un_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        un_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string pass = 3;
    public static final int PASS_FIELD_NUMBER = 3;
    private java.lang.Object pass_;
    /**
     * <code>required string pass = 3;</code>
     */
    public boolean hasPass() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string pass = 3;</code>
     */
    public java.lang.String getPass() {
      java.lang.Object ref = pass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pass = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPassBytes() {
      java.lang.Object ref = pass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string nn = 4;
    public static final int NN_FIELD_NUMBER = 4;
    private java.lang.Object nn_;
    /**
     * <code>required string nn = 4;</code>
     */
    public boolean hasNn() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string nn = 4;</code>
     */
    public java.lang.String getNn() {
      java.lang.Object ref = nn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string nn = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNnBytes() {
      java.lang.Object ref = nn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 sex = 5;
    public static final int SEX_FIELD_NUMBER = 5;
    private int sex_;
    /**
     * <code>required int32 sex = 5;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 sex = 5;</code>
     */
    public int getSex() {
      return sex_;
    }

    // required int32 ico = 6;
    public static final int ICO_FIELD_NUMBER = 6;
    private int ico_;
    /**
     * <code>required int32 ico = 6;</code>
     */
    public boolean hasIco() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 ico = 6;</code>
     */
    public int getIco() {
      return ico_;
    }

    private void initFields() {
      uid_ = 0;
      un_ = "";
      pass_ = "";
      nn_ = "";
      sex_ = 0;
      ico_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPass()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIco()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUnBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPassBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNnBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, sex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, ico_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUnBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPassBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNnBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sex_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, ico_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.data.UserInfo.uInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.data.UserInfo.uInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.data.UserInfo.uInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.data.UserInfo.uInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.data.UserInfo.uInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.data.UserInfo.uInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.data.UserInfo.uInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.data.UserInfo.uInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.data.UserInfo.uInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.data.UserInfo.uInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.data.UserInfo.uInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.data.uInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.data.UserInfo.uInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.data.UserInfo.internal_static_com_data_uInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.data.UserInfo.internal_static_com_data_uInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.data.UserInfo.uInfo.class, com.data.UserInfo.uInfo.Builder.class);
      }

      // Construct using com.data.UserInfo.uInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        un_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        pass_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        nn_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        ico_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.data.UserInfo.internal_static_com_data_uInfo_descriptor;
      }

      public com.data.UserInfo.uInfo getDefaultInstanceForType() {
        return com.data.UserInfo.uInfo.getDefaultInstance();
      }

      public com.data.UserInfo.uInfo build() {
        com.data.UserInfo.uInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.data.UserInfo.uInfo buildPartial() {
        com.data.UserInfo.uInfo result = new com.data.UserInfo.uInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.un_ = un_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pass_ = pass_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nn_ = nn_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ico_ = ico_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.data.UserInfo.uInfo) {
          return mergeFrom((com.data.UserInfo.uInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.data.UserInfo.uInfo other) {
        if (other == com.data.UserInfo.uInfo.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasUn()) {
          bitField0_ |= 0x00000002;
          un_ = other.un_;
          onChanged();
        }
        if (other.hasPass()) {
          bitField0_ |= 0x00000004;
          pass_ = other.pass_;
          onChanged();
        }
        if (other.hasNn()) {
          bitField0_ |= 0x00000008;
          nn_ = other.nn_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasIco()) {
          setIco(other.getIco());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasUn()) {
          
          return false;
        }
        if (!hasPass()) {
          
          return false;
        }
        if (!hasNn()) {
          
          return false;
        }
        if (!hasSex()) {
          
          return false;
        }
        if (!hasIco()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.data.UserInfo.uInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.data.UserInfo.uInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 uid = 1;
      private int uid_ ;
      /**
       * <code>required int32 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        onChanged();
        return this;
      }

      // required string un = 2;
      private java.lang.Object un_ = "";
      /**
       * <code>required string un = 2;</code>
       */
      public boolean hasUn() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string un = 2;</code>
       */
      public java.lang.String getUn() {
        java.lang.Object ref = un_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          un_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string un = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUnBytes() {
        java.lang.Object ref = un_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          un_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string un = 2;</code>
       */
      public Builder setUn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        un_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string un = 2;</code>
       */
      public Builder clearUn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        un_ = getDefaultInstance().getUn();
        onChanged();
        return this;
      }
      /**
       * <code>required string un = 2;</code>
       */
      public Builder setUnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        un_ = value;
        onChanged();
        return this;
      }

      // required string pass = 3;
      private java.lang.Object pass_ = "";
      /**
       * <code>required string pass = 3;</code>
       */
      public boolean hasPass() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string pass = 3;</code>
       */
      public java.lang.String getPass() {
        java.lang.Object ref = pass_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          pass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string pass = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPassBytes() {
        java.lang.Object ref = pass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pass = 3;</code>
       */
      public Builder setPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pass = 3;</code>
       */
      public Builder clearPass() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pass_ = getDefaultInstance().getPass();
        onChanged();
        return this;
      }
      /**
       * <code>required string pass = 3;</code>
       */
      public Builder setPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        pass_ = value;
        onChanged();
        return this;
      }

      // required string nn = 4;
      private java.lang.Object nn_ = "";
      /**
       * <code>required string nn = 4;</code>
       */
      public boolean hasNn() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string nn = 4;</code>
       */
      public java.lang.String getNn() {
        java.lang.Object ref = nn_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string nn = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNnBytes() {
        java.lang.Object ref = nn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string nn = 4;</code>
       */
      public Builder setNn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string nn = 4;</code>
       */
      public Builder clearNn() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nn_ = getDefaultInstance().getNn();
        onChanged();
        return this;
      }
      /**
       * <code>required string nn = 4;</code>
       */
      public Builder setNnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        nn_ = value;
        onChanged();
        return this;
      }

      // required int32 sex = 5;
      private int sex_ ;
      /**
       * <code>required int32 sex = 5;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 sex = 5;</code>
       */
      public int getSex() {
        return sex_;
      }
      /**
       * <code>required int32 sex = 5;</code>
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sex = 5;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sex_ = 0;
        onChanged();
        return this;
      }

      // required int32 ico = 6;
      private int ico_ ;
      /**
       * <code>required int32 ico = 6;</code>
       */
      public boolean hasIco() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 ico = 6;</code>
       */
      public int getIco() {
        return ico_;
      }
      /**
       * <code>required int32 ico = 6;</code>
       */
      public Builder setIco(int value) {
        bitField0_ |= 0x00000020;
        ico_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ico = 6;</code>
       */
      public Builder clearIco() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ico_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.data.uInfo)
    }

    static {
      defaultInstance = new uInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.data.uInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_data_uInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_data_uInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016UserInfo.proto\022\010com.data\"T\n\005uInfo\022\013\n\003u" +
      "id\030\001 \002(\005\022\n\n\002un\030\002 \002(\t\022\014\n\004pass\030\003 \002(\t\022\n\n\002nn" +
      "\030\004 \002(\t\022\013\n\003sex\030\005 \002(\005\022\013\n\003ico\030\006 \002(\005B\024\n\010com." +
      "dataB\010UserInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_data_uInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_data_uInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_data_uInfo_descriptor,
              new java.lang.String[] { "Uid", "Un", "Pass", "Nn", "Sex", "Ico", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
